name: gh-sync
on:
  workflow_dispatch:
  schedule:
    - cron: "28 3 * * *"
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
         fetch-depth: 0

      - name: git config
        run: |-
          git config --global user.name "Github Actions"
          git config --global user.email "actions@gmail.com"
      - name: sync
        run: |-
          git checkout gh-pages
          git checkout main data.js
          git status
          git commit -m "update by github actions"
          git push
